name: Deploy ZIP to GitHub Pages 

on:
  push:
    branches: ["main"]
    paths:
      - "site.zip"
      - ".github/workflows/deploy-zip.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip site.zip
        run: |
          mkdir build
          unzip -o site.zip -d build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
        id: deployment
